spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: admin
  devtools:
    livereload:
      # 정적 리소스에 변화가 있을 때 바로 반영한다.
      enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    # thymeleaf에 대한 캐시를 남기지 않는다. cache=false 설정(운영시는 true)
    cache: false
    # templates 디렉토리에 파일이 있는지 없는지 체크, 없으면 에러를 발생시킨다.
    check-template-location: true
    mode: HTML
  web:
    resources:
      static-locations: classpath:static/


